const TRANSLATE_SUCCESS = 'TRANSLATE_SUCCESS'
const TRANSLATE_ATTEMPT = 'TRANSLATE_ATTEMPT'
const TRANSLATE_FAILURE = 'TRANSLATE_FAILURE'
const CHANGE_INITIAL_LANGUAGE = 'CHANGE_INITIAL_LANGUAGE'
const CHANGE_FINAL_LANGUAGE = 'CHANGE_FINAL_LANGUAGE'
const ORIGINAL_TEXT = 'ORIGINAL_TEXT'
const ADD_NEW_PLAYER = 'ADD_NEW_PLAYER'
const PLAY_AGAIN = 'PLAY_AGAIN'

const Types = {
    TRANSLATE_SUCCESS,
    TRANSLATE_ATTEMPT,
    TRANSLATE_FAILURE,
    CHANGE_INITIAL_LANGUAGE,
    CHANGE_FINAL_LANGUAGE,
    ORIGINAL_TEXT,
    ADD_NEW_PLAYER,
    PLAY_AGAIN
}

export default Types